defaults:
  - finngen_finemapping_ingestion

finngen_finemapping_results_path: ${datasets.finngen_finemapping_results_path}
finngen_finemapping_summaries_path: ${datasets.finngen_finemapping_summaries_path}
finngen_release_prefix: ${datasets.finngen_release_prefix}
finngen_finemapping_out: ${datasets.finngen_finemapping_out}
