defaults:
  - gwas_catalog_ingestion

catalog_study_files: ${datasets.gwas_catalog_studies}
catalog_ancestry_files: ${datasets.gwas_catalog_ancestries}
catalog_associations_file: ${datasets.gwas_catalog_associations}
catalog_sumstats_lut: ${datasets.gwas_catalog_sumstats_lut}
variant_annotation_path: ${datasets.variant_annotation}
catalog_studies_out: ${datasets.gwas_catalog_study_index}
catalog_associations_out: ${datasets.gwas_catalog_study_locus_folder}/gwas_catalog_curated_associations
gwas_catalog_study_curation_file: ${datasets.gwas_catalog_study_curation}
inclusion_list_path: ${datasets.gwas_catalog_curated_inclusion_list}
