defaults:
  - locus_to_gene

run_mode: predict
model_path: null
predictions_path: ${datasets.l2g_predictions}
feature_matrix_path: ${datasets.l2g_feature_matrix}
credible_set_path: ${datasets.credible_set}
variant_gene_path: ${datasets.variant_to_gene}
colocalisation_path: ${datasets.colocalisation}
study_index_path: ${datasets.study_index}
