defaults:
  - locus_to_gene

run_mode: train
wandb_run_name: null
perform_cross_validation: false
model_path: ${datasets.l2g_model}
predictions_path: ${datasets.l2g_predictions}
credible_set_path: ${datasets.credible_set}
variant_gene_path: ${datasets.v2g}
colocalisation_path: ${datasets.colocalisation}
study_index_path: ${datasets.study_index}
gold_standard_curation_path: ${datasets.l2g_gold_standard_curation}
gene_interactions_path: ${datasets.gene_interactions}
hyperparameters:
  max_depth: 5
  loss_function: binary:logistic
