---
work_path: /mnt/disks/work
log_level: INFO

scratchpad:
  gc_stats_uri: "https://www.ebi.ac.uk/gwas/api/search/stats"
  gc_bucket: "gs://gwas_catalog_inputs"
  gc_ftp: "ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases"


steps:
  gwas_catalog_release:
    - name: crawl release metadata
      stats_uri: ${gc_stats_uri}
      destination_template: '${gc_bucket}/gentroutils/{release_date}/stats.json'
      promote: true

    - name: fetch associations
      stats_uri: ${gc_stats_uri}
      source_template: '${gc_ftp}/{release_date}/gwas-catalog-associations_ontology-annotated.tsv'
      destination_template: '${gc_bucket}/gentroutils/{release_date}/gwas_catalog_associations_ontology_annotated.tsv'
      promote: true

    - name: fetch studies
      stats_uri: ${gc_stats_uri}
      source_template: '${gc_ftp}/{release_date}/gwas-catalog-download-studies-v1.0.3.1.txt'
      destination_template: '${gc_bucket}/gentroutils/{release_date}/gwas_catalog_download_studies.tsv'
      promote: true

    - name: fetch ancestries
      stats_uri: ${gc_stats_uri}
      source_template: '${gc_ftp}/{release_date}/gwas-catalog-download-ancestries-v1.0.3.1.txt'
      destination_template: '${gc_bucket}/gentroutils/{release_date}/gwas_catalog_download_ancestries.tsv'
      promote: true

    - name: curation study
      requires:
        - fetch studies
      previous_curation: '${gc_bucket}/curation/latest/curated/GWAS_Catalog_study_curation.tsv'
      studies: '${gc_bucket}/gentroutils/latest/gwas_catalog_download_studies.tsv'
      destination_template: '${gc_bucket}/curation/{release_date}/raw/GWAS_Catalog_study_curation.tsv'
      promote: true