r"""Operators for batch job.

The idea behind the batch job operators is to provide a generic way to create
batch jobs.

The `BatchIndexOperator` is a
[facade](https://refactoring.guru/design-patterns/facade) class that allows for
finding the manifest generator class by its label `manifest_generator_label` and
then generating the batch index using discovered generator and its specification
defined in `manifest_generator_specs`.

The batch index generated by the class following the `ProtoManifestGenerator`
interface should generate initial manifest - table where each row contains a
[google batch Task](https://cloud.google.com/batch/docs/get-started).

After the batch index is generated, the `BatchJobOperator` will call the
`BatchIndex.partition` with `max_task_count` as the upper limit for the number
of tasks in a single batch job. The method will partition the initial manifest
into smaller chunks (BatchIndexRow).

Each manifest chunk will then be used to create the `environment` for the single
batch job.

```
                                                        / BatchIndexRow -> BatchJobOperator
BatchIndexOperator -> ManifestGenerator -> BatchIndex -
                                                        \ BatchIndexRow -> BatchJobOperator
```
"""
