---
dataproc:
  python_main_module: gs://genetics_etl_python_playground/initialisation/cli.py
  cluster_metadata:
    GENTROPY_REF: v2.3.0-rc.5
  cluster_init_script: gs://genetics_etl_python_playground/initialisation/install_dependencies_on_cluster.sh
  cluster_name: otg-credible-set-qc
  autoscaling_policy: otg-etl

nodes:
  - id: gwas_catalog_sumstats_susie_credible_set_qc
    kind: Task
    prerequisites: []
    params:
      step: credible_set_qc
      step.credible_sets_path: gs://gwas_catalog_sumstats_susie/credible_set_datasets_20250204
      step.output_path: gs://gwas_catalog_sumstats_susie/credible_set_clean/20250204
      step.p_value_threshold: 1.0e-5
      step.purity_min_r2: 0.25
      step.n_partitions: 250
      step.clump: false
      step.session.write_mode: overwrite
      step.session.start_hail: true

  - id: ukb_ppp_eur_data_credible_set_qc
    kind: Task
    prerequisites: []
    params:
      step: credible_set_qc
      step.credible_sets_path: gs://ukb_ppp_eur_data/credible_set_datasets/susie/20250129
      step.output_path: gs://ukb_ppp_eur_data/credible_set_clean/20250129
      step.p_value_threshold: 1.0e-5
      step.purity_min_r2: 0.25
      step.n_partitions: 50
      step.clump: false
      step.session.write_mode: overwrite
      step.session.start_hail: true
