---
environment_specs:
  - name: Prod
    vars:
      input_path: gs://finngen-public-data-r12
      output_path: gs://finngen_data/r12
      curation_tag: '26.05'

env: Prod

dataproc:
  cluster_name: otg-ingestion-finngen
  autoscaling_policy: finngen-preprocess
  cluster_metadata:
    GENTROPY_REF: v3.2.0
  master_disk_size: 2000
  num_workers: 6

nodes:
  - id: finngen_studies
    kind: Task
    prerequisites: []
    params:
      step: finngen_studies
      step.finngen_study_index_out: '{output_path}/study_index'
      step.finngen_phenotype_table_url: 'https://r12.finngen.fi/api/phenos'
      step.finngen_release_prefix: FINNGEN_R12
      step.finngen_summary_stats_url_prefix: '{input_path}/summary_stats/finngen_R12_'
      step.sample_size: 500_348
      step.finngen_summary_stats_url_suffix: '.gz'
      step.efo_curation_mapping_url: 'https://raw.githubusercontent.com/opentargets/curation/refs/tags/{curation_tag}/mappings/disease/manual_string.tsv'
      step.session.write_mode: overwrite
      step.session.start_hail: true
  - id: finngen_finemapping_ingestion
    kind: Task
    prerequisites: []
    params:
      step: finngen_finemapping_ingestion
      step.finngen_finemapping_out: '{output_path}/credible_set_datasets/susie'
      step.finngen_susie_finemapping_snp_files: '{input_path}/finemap/full/susie/*.snp.bgz'
      step.finngen_susie_finemapping_cs_summary_files: '{input_path}/finemap/summary/*SUSIE.cred.summary.tsv'
      step.finngen_finemapping_lead_pvalue_threshold: 1e-5
      step.finngen_release_prefix: FINNGEN_R12
      step.session.start_hail: true
      step.session.write_mode: overwrite
