---
dataproc:
  python_main_module: gs://genetics_etl_python_playground/initialisation/cli.py
  cluster_metadata:
    GENTROPY_REF:  v2.3.0-rc.5
  cluster_init_script: gs://genetics_etl_python_playground/initialisation/install_dependencies_on_cluster.sh

  cluster_name: foldx-ingestion
  autoscaling_policy: otg-etl
  allow_efm: false
  num_workers: 2

nodes:
  - id: foldx_variant_annotation_ingestion
    kind: Task
    prerequisites: []
    params:
      step: foldx_integration
      step.foldx_dataset_path: gs://otar013-ppp/OTAR2081_foldx/foldx_export.parquet
      step.plddt_threshold: 0.7
      step.annotation_path: gs://otar013-ppp/OTAR2081_foldx/foldx_variant_annotation
