---
steps:
  biosample:
    params:
      step: biosample_index
      step.session.write_mode: overwrite
      step.session.output_partitions: 1
      # INPUTS
      step.cell_ontology_input_path: '{{release_uri}}/input/biosample/cl.json'
      step.uberon_input_path: '{{release_uri}}/input/biosample/uberon.json'
      step.efo_input_path: '{{release_uri}}/input/biosample/efo.json'
      # OUTPUTS
      step.biosample_index_path: '{{release_uri}}/output/biosample'

  study:
    params:
      step: study_validation
      step.session.write_mode: overwrite
      step.session.output_partitions: 1
      step.invalid_qc_reasons:
        - UNRESOLVED_TARGET
        - UNRESOLVED_DISEASE
        - UNKNOWN_STUDY_TYPE
        - DUPLICATED_STUDY
        - UNKNOWN_BIOSAMPLE
        - FAILED_MEAN_BETA_CHECK
        - FAILED_PZ_CHECK
        - FAILED_GC_LAMBDA_CHECK
        - NO_OT_CURATION
        - CASE_CASE_STUDY_DESIGN
      # INPUTS
      step.study_index_path:
        - gs://gwas_catalog_top_hits/study_index
        - gs://gwas_catalog_sumstats_susie/study_index
        - gs://gwas_catalog_sumstats_pics/study_index
        - gs://eqtl_catalogue_data/study_index
        - gs://ukb_ppp_eur_data/study_index
        - gs://finngen_data/r12/study_index
      step.target_index_path: '{{release_uri}}/output/target'
      step.disease_index_path: '{{release_uri}}/output/disease'
      step.biosample_index_path: '{{release_uri}}/output/biosample'
      # OUTPUTS
      step.valid_study_index_path: '{{release_uri}}/output/study'
      step.invalid_study_index_path: '{{release_uri}}/excluded/study'

  credible_set:
    params:
      step: credible_set_validation
      step.session.write_mode: overwrite
      step.session.output_partitions: 25
      step.invalid_qc_reasons:
        - DUPLICATED_STUDYLOCUS_ID
        - AMBIGUOUS_STUDY
        - MISSING_STUDY
        - NO_GENOMIC_LOCATION_FLAG
        - COMPOSITE_FLAG
        - INCONSISTENCY_FLAG
        - SUBSIGNIFICANT_FLAG
        - LD_CLUMPED
        - IN_MHC
        - REDUNDANT_PICS_TOP_HIT
        - EXPLAINED_BY_SUSIE
        - WINDOW_CLUMPED
        - NON_MAPPED_VARIANT_FLAG
        - INVALID_VARIANT_IDENTIFIER
        - INVALID_CHROMOSOME
        - TOP_HIT_AND_SUMMARY_STATS
      step.trans_qtl_threshold: 5_000_000
      # INPUTS
      step.study_locus_path:
        - gs://gwas_catalog_top_hits/credible_sets/
        - gs://gwas_catalog_sumstats_pics/credible_sets/
        - gs://gwas_catalog_sumstats_susie/credible_set_clean/20250721/
        - gs://eqtl_catalogue_data/credible_set_datasets/eqtl_catalogue_susie_patched_v2/
        - gs://ukb_ppp_eur_data/credible_set_clean/20250129/
        - gs://finngen_data/r12/credible_set_datasets/susie/
      step.study_index_path: '{{release_uri}}/output/study'
      step.target_index_path: '{{release_uri}}/output/target'
      # OUTPUTS
      step.valid_study_locus_path: '{{release_uri}}/output/credible_set'
      step.invalid_study_locus_path: '{{release_uri}}/excluded/credible_set'

  colocalisation_coloc:
    params:
      step: colocalisation
      step.session.write_mode: overwrite
      step.session.output_partitions: 25
      step.colocalisation_method: Coloc
      +step.colocalisation_method_params: '{priorc1: 1e-4, priorc2: 1e-4, priorc12: 1e-5}'
      +step.session.extended_spark_conf: "{spark.executor.memory: '25g', spark.executor.memoryOverhead: '1g', spark.executor.cores: '4'}"
      # INPUTS
      step.credible_set_path: '{{release_uri}}/output/credible_set'
      # OUTPUTS
      step.coloc_path: '{{release_uri}}/output/colocalisation_coloc'

  colocalisation_ecaviar:
    params:
      step: colocalisation
      step.session.write_mode: overwrite
      step.session.output_partitions: 25
      step.colocalisation_method: ECaviar
      +step.session.extended_spark_conf: "{spark.executor.memory: '25g', spark.executor.memoryOverhead: '1g', spark.executor.cores: '4'}"
      # INPUTS
      step.credible_set_path: '{{release_uri}}/output/credible_set'
      # OUTPUTS
      step.coloc_path: '{{release_uri}}/output/colocalisation_ecaviar'

  colocalisation_colocpip_and_ecaviar:
    params:
      step: colocalisation
      step.session.write_mode: overwrite
      step.session.output_partitions: 25
      step.colocalisation_method: coloc_pip_ecaviar
      +step.session.extended_spark_conf: "{spark.executor.memory: '25g', spark.executor.memoryOverhead: '1g', spark.executor.cores: '4'}"
      # INPUTS
      step.credible_set_path: '{{release_uri}}/output/credible_set'
      # OUTPUTS
      step.coloc_path: '{{release_uri}}/output/colocalisation'

  variant_partition:
    params:
      step: variant_to_vcf
      step.partition_size: 2_000 # approximate num of variants per partition!
      step.session.write_mode: overwrite
      # INPUTS
      step.source_paths:
        - '{{release_uri}}/input/evidence/uniprot_variants.json.gz'
        - '{{release_uri}}/input/evidence/eva.json.gz'
        - '{{release_uri}}/input/pharmacogenomics/pharmacogenomics.json.gz'
        - '{{release_uri}}/output/credible_set'
      step.source_formats:
        - json
        - json
        - json
        - parquet
      # OUTPUTS
      step.output_path: '{{release_uri}}/intermediate/variant_partition'

  variant_annotation:
    cluster: false
    google_batch:
      resource_specs:
        cpu_milli: 2000
        memory_mib: 2000
        boot_disk_mib: 10000
      task_specs:
        max_retry_count: 10 # retry up to 10 times due to SPOT 50001 preemption errors
        max_run_duration: '2h'
      policy_specs:
        machine_type: n1-standard-4
      image: 'europe-west1-docker.pkg.dev/open-targets-eu-dev/vep/custom_ensembl_vep:{{vep_version}}'
      entrypoint: /bin/sh
      parallelism: 500 # max number of VEP tasks run at a time in parallel
    params:
      # INPUTS
      vep_cache_path: gs://vep_cache_data/vep/cache
      vcf_input_path: '{{release_uri}}/intermediate/variant_partition'
      # OUTPUTS
      vep_output_path: '{{release_uri}}/intermediate/variant_annotation'

  variant:
    params:
      step: variant_index
      step.session.write_mode: overwrite
      step.session.output_partitions: 25
      # INPUTS
      step.vep_output_json_path: '{{release_uri}}/intermediate/variant_annotation'
      step.variant_annotations_path:
        - gs://gnomad_data_2/v4.1/variant_index
      step.amino_acid_change_annotations:
        - gs://otar013-ppp/OTAR2081_foldx/foldx_variant_annotation
      # OUTPUTS
      step.variant_index_path: '{{release_uri}}/output/variant'

  l2g_feature_matrix:
    params:
      step: locus_to_gene_feature_matrix
      step.session.write_mode: overwrite
      +step.session.extended_spark_conf: "{spark.sql.autoBroadcastJoinThreshold:'-1'}"
      # INPUTS
      step.credible_set_path: '{{release_uri}}/output/credible_set'
      step.variant_index_path: '{{release_uri}}/output/variant'
      step.colocalisation_path: '{{release_uri}}/output/colocalisation'
      step.study_index_path: '{{release_uri}}/output/study'
      step.target_index_path: '{{release_uri}}/output/target'
      # OUTPUTS
      step.feature_matrix_path: '{{release_uri}}/intermediate/l2g_feature_matrix'

  l2g_training:
    params:
      step: locus_to_gene
      step.session.write_mode: overwrite
      step.run_mode: train
      step.wandb_run_name: '{{l2g_training_version}}'
      step.cross_validate: false
      step.hf_hub_repo_id: opentargets/locus_to_gene_{{l2g_training_version}}
      step.hf_model_commit_message: 'chore: update model base model for {{l2g_training_version}} run'
      +step.session.extended_spark_conf: "{spark.kryoserializer.buffer.max:500m, spark.sql.autoBroadcastJoinThreshold:'-1'}"
      # INPUTS
      step.credible_set_path: '{{release_uri}}/output/credible_set'
      step.feature_matrix_path: '{{release_uri}}/intermediate/l2g_feature_matrix'
      step.gold_standard_curation_path: '{{release_uri}}/input/l2g/gold_standard.json'
      # OUTPUTS
      step.model_path: '{{release_uri}}/etc/model/locus_to_gene_model/classifier.skops'

  l2g_prediction:
    cluster: false
    google_batch_index_specs:
      manifest_generator_label: "gentropy-step"
      manifest_generator_specs:
        commands:
          - -c
          - "gentropy"
        options:
          step: locus_to_gene
          step.session.write_mode: append
          step.run_mode: predict
          step.session.output_partitions: 1
          step.l2g_threshold: 0.05
          step.download_from_hub: true
          step.explain_predictions: true
          +step.session.extended_spark_conf: "{spark.rpc.message.maxSize:'2046'}"
          # INPUTS
          step.hf_hub_repo_id: 'opentargets/locus_to_gene_{{l2g_training_version}}'
          step.feature_matrix_path: '{{release_uri}}/intermediate/l2g_feature_matrix'
          step.credible_set_path: '$cs_partition' # The env value $cs_partition differs within each machine.
          # OUTPUTS
          step.predictions_path: '{{release_uri}}/output/l2g_prediction'
        manifest_kwargs:
          # Job partitioninig depends on the number of credible_set parquet files.
          input_glob: '{{release_uri}}/output/credible_set/**.parquet'
    google_batch:
      entrypoint: /usr/bin/bash
      image: 'europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/gentropy:{{gentropy_version}}'
      resource_specs:
        cpu_milli: 2000
        memory_mib: 7000
        boot_disk_mib: 4000
      task_specs:
        max_retry_count: 0
        max_run_duration: "1h"
      policy_specs:
        machine_type: n1-standard-2

  l2g_evidence:
    params:
      step: locus_to_gene_evidence
      step.session.write_mode: overwrite
      step.locus_to_gene_threshold: 0.05
      # INPUTS
      step.credible_set_path: '{{release_uri}}/output/credible_set'
      step.locus_to_gene_predictions_path: '{{release_uri}}/output/l2g_prediction'
      step.study_index_path: '{{release_uri}}/output/study'
      # OUTPUTS
      step.evidence_output_path: '{{release_uri}}/intermediate/evidence/l2g_evidence'
