---
environments:
  - name: prod
    sentinels:
      gentroutils_version: '3.1.0'
      gentropy_version: '2.4.0'
      project_id: 'open-targets-genetics-dev'
      input_path: gs://gwas_catalog_inputs
      output_path: gs://gwas_catalog_top_hits
      sync_date: '20250708'
      gnomad_path: gs://gnomad_data_2
      gc_stats_uri: "https://www.ebi.ac.uk/gwas/api/search/stats"
      gc_ftp: "ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases"

env: prod
staging_bucket: '{input_path}'

steps:
  gentroutils_gwas_catalog_release_ingestion:
    vm: top_hits
  gentropy_top_hits_ingestion:
    depends_on: 
      - gentroutils_gwas_catalog_release_ingestion
    cluster: top_hits
  gentropy_top_hits_ld_based_clumping:
    depends_on: 
      - gentropy_top_hits_ingestion
    cluster: top_hits
  gentropy_top_hits_pics:
    depends_on: 
      - gentropy_top_hits_ld_based_clumping
    cluster: top_hits


