---
environment_specs:
  - name: Test
    vars:
      sumstats_path: gs://gwas_catalog_inputs/harmonised_summary_statistics
      ldscore_base_path: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/inputs/custom_panel
      study_index_path: gs://gwas_catalog_sumstats_susie/study_index/
      outputs_dir: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/outputs/gentropy_all_sumstats_2606
      gentropy_image: europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/gentropy:3.3.0-dev.14

  - name: Prod
    vars:
      sumstats_path: gs://gwas_catalog_inputs/harmonised_summary_statistics
      ldscore_base_path: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/inputs/custom_panel
      study_index_path: gs://gwas_catalog_sumstats_susie/study_index/
      outputs_dir: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/outputs/gentropy_all_sumstats_2606
      gentropy_image: europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/gentropy:3.3.0-dev.14

env: Test

nodes:
  - id: heritability_estimate
    kind: Task
    prerequisites: []
    google_batch_index_specs:
      pointer: heritability_estimate
      max_task_count: 1000
      generator_specs:
        generator_options:
          input_glob: "{sumstats_path}"
          output_prefix: "{outputs_dir}/heritability_estimates"

    google_batch:
      job:
        task_group:
          parallelism: 200
          task_environments:
            environments: []  # populated at runtime by BatchIndexOperator
          task_config:
            max_retry_count: 2
            max_run_duration: "1h"
            instance_resource_spec:
              cpu_milli: 4000
              memory_mib: 26000
              boot_disk_mib: 16000
            runnable_spec:
              image_uri: "{gentropy_image}"
              entrypoint: /usr/bin/bash
              inline_commands:
                - '-c'
                - >-
                  gentropy
                  step=heritability_estimate
                  step.session.write_mode=overwrite
                  step.session.output_partitions=1
                  step.summary_statistics_input_path=$INPUT_PARTITION
                  step.study_index_input_path={study_index_path}
                  step.ldscore_base_path={ldscore_base_path}
                  step.heritability_output_path=$OUTPUT_PARTITION
                  "+step.session.extended_spark_conf={spark.jars:https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop3-latest.jar,spark.hadoop.fs.gs.requester.pays.mode:CUSTOM,spark.hadoop.fs.gs.requester.pays.buckets:open-targets-data-releases,spark.hadoop.fs.gs.requester.pays.project.id:open-targets-genetics-dev,spark.driver.memory:48g,spark.executor.memory:48g,spark.driver.memoryOverhead:8g,spark.executor.memoryOverhead:8g}"
        allocation:
          instance:
            machine_type: n2-highmem-4
            provisioning_model: SPOT
        logs: {}
