---
environment_specs:
  - name: Test
    vars:
      sumstats_path: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/sumstats_subset
      ldscore_base_path: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/inputs/gnomad/ldscores/full
      study_index_path: gs://open-targets-data-releases/25.12/output/study
      outputs_dir: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/output
      gentropy_image: europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/gentropy:3.3.0-dev.5

  - name: Prod
    vars:
      sumstats_path: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/sumstats_subset
      ldscore_base_path: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/inputs/gnomad/ldscores/full
      study_index_path: gs://open-targets-data-releases/25.12/output/study
      outputs_dir: gs://genetics-portal-dev-analysis/xg1/LDSC_pyspark/output
      gentropy_image: europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/gentropy:3.3.0-dev.5

env: Test

nodes:
  - id: heritability_estimate
    kind: Task
    prerequisites: []
    cluster: false
    google_batch_index_specs:
      manifest_generator_label: heritability-estimate
      max_task_count: 20
      manifest_generator_specs:
        commands:
          - -c
          - gentropy
        options:
          step: heritability_estimate
          step.session.write_mode: overwrite
          step.session.output_partitions: 1
          step.summary_statistics_input_path: "$INPUT_PARTITION"
          step.study_index_input_path: "{study_index_path}"
          step.ldscore_base_path: "{ldscore_base_path}"
          step.heritability_output_path: "$OUTPUT_PARTITION"
          +step.session.extended_spark_conf: '{spark.jars:https://storage.googleapis.com/hadoop-lib/gcs/gcs-connector-hadoop3-latest.jar,spark.hadoop.fs.gs.requester.pays.mode:"CUSTOM",spark.hadoop.fs.gs.requester.pays.buckets:"open-targets-data-releases",spark.hadoop.fs.gs.requester.pays.project.id:"open-targets-genetics-dev", spark.driver.memory:48g,spark.executor.memory:48g,spark.driver.memoryOverhead:8g,spark.executor.memoryOverhead:8g}'
        manifest_kwargs:
          input_glob: "{sumstats_path}"
          output_prefix: "{outputs_dir}/heritability_estimates"

    google_batch:
      entrypoint: /usr/bin/bash
      image: "{gentropy_image}"
      resource_specs:
        cpu_milli: 8000
        memory_mib: 64000
        boot_disk_mib: 16000
      task_specs:
        max_retry_count: 2
        max_run_duration: "1h"
      policy_specs:
        machine_type: n2d-highmem-8