---
environment_specs:
  - name: Prod
    vars:
      output_path: gs://gwas_catalog_sumstats_susie
      GENTROPY_REF: 2.4.2-rc.4

env: Prod

nodes:
  - id: generate_manifests
    kind: Task
    prerequisites: []
    params:
      collected_loci_path: '{output_path}/study_locus_lb_clumped'
      manifest_prefix: '{output_path}/finemapping_manifests/20250721'
      output_path: '{output_path}/credible_set_datasets'
      #!WARNING: DO NOT CHANGE THE DATE for the log_path, as it is used to back reference the already fine-mapped loci.
      log_path: '{output_path}/finemapping_logs/20250204'
      max_records_per_chunk: 40_000

  - id: finemapping_batch_job
    kind: Task
    prerequisites:
      - generate_manifests
    params:
      study_index_path: '{output_path}/study_index'
    google_batch:
      image: 'europe-west1-docker.pkg.dev/open-targets-genetics-dev/gentropy-app/gentropy:{GENTROPY_REF}'
      entrypoint: /usr/bin/bash
      resource_specs:
        cpu_milli: 4000
        memory_mib: 25_000
        boot_disk_mib: 20_000
      task_specs:
        max_retry_count: 1
        max_run_duration: "7200s"
      policy_specs:
        machine_type: n2-highmem-4
