---
environment_specs:
  - name: Prod
    vars:
      root_path: gs://ukb_ppp_eur_data
      date: '20250129'
      gentropy_ref: '2.0.2-rc.2'
  - name: Test
    vars:
      root_path: gs://ot_orchestration/test/ukb_ppp_eur_data
      date: '20250129'
      gentropy_ref: '2.0.2-rc.2'

env: Prod

nodes:
  - id: generate_finemapping_index
    kind: Task
    prerequisites: []
    google_batch_index_specs:
      pointer: finemapping
      max_task_count: 40000
      generator_specs:
        generator_options:
          collected_loci_path: '{root_path}/study_locus_lb_clumped'
          manifest_output_path: '{root_path}/finemapping_manifests/{date}/manifest.csv'
          output_path: '{root_path}/credible_set_datasets/susie/{date}'
          log_path: '{root_path}/finemapping_logs/{date}'

  - id: finemapping_batch_job
    kind: Task
    prerequisites:
      - generate_finemapping_index
    google_batch:
      job:
        task_group:
          parallelism: 40000
          task_environments:
            environments: [] # populated at runtime by BatchIndexOperator
          task_config:
            max_retry_count: 5
            max_run_duration: '7200s'
            instance_resource_spec:
              cpu_milli: 4000
              memory_mib: 25000
              boot_disk_mib: 20000
            runnable_spec:
              image_uri: 'europe-west1-docker.pkg.dev/open-targets-genetics-dev/gentropy-app/gentropy:{gentropy_ref}'
              entrypoint: /bin/sh
              script_file: susie_finemap.sh
              script_variables:
                study_index_path: '{root_path}/study_index'
                study_locus_manifest_path: '{root_path}/finemapping_manifests/{date}/manifest.csv'
        allocation:
          instance:
            machine_type: n2-highmem-4
            provisioning_model: SPOT
        logs: {}
