---
release_name: '25.06'

# If `is_dev` is true:
#   * the bucket used for the run will be `open-targets-pipeline-runs`
#   * the prefix inside the bucket will be `run_name`
#         which defaults to a timestamp if not provided.
is_dev: true
run_name: 'szsz/25.06-testrun-4'

# Whether this will be a partner preview platform release (PPP)
is_ppp: false

# Versions for software and data
pis_version: '25.2.1'
pts_version: '25.0.2-beta.4'
etl_version: '25.2.0-beta.4'
gentropy_version: '2.3.0-rc.4'
vep_version: 'release_114.0'

chembl_version: '35'
efo_version: '3.77.0'
ensembl_version: '114'

# Dependency graph
# ----------------
# The following section defines the dependencies between the different steps in
# the pipeline.
#
# IMPORTANT: any dependency change has to be reflected here _manually_.
#
# IMPORTANT: only direct dependencies are defined. Take care when removing one,
#      and always double check if instead of just deleting, you have to change
#      it for another step that is further upstream.
#
# Note: steps that can run in parallel are separated in blocks by a blank line,
#      which means each block depends on the previous block.
#
# It could be possible to generate this automatically from the file input for
# each step, but given the current fast pace of changes throughout the whole
# pipeline, it is not worth the effort to implement this until things have
# stabilised.
#
steps:
  # PIS STEPS
  pis_biosample:
  pis_disease:
  pis_drug:
  pis_evidence:
  pis_evidence_ppp:
    ppp_only: true
  pis_expression:
  pis_go:
  pis_l2g:
  pis_interaction:
  pis_literature:
  pis_mouse_phenotype:
  pis_openfda:
  pis_otar:
    ppp_only: true
  pis_pharmacogenomics:
  pis_reactome:
  pis_so:
  pis_target:
  pis_target_engine:

  # PTS STEPS
  pts_disease:
    depends_on:
      - pis_disease
  pts_expression:
    depends_on:
      - pis_expression
  pts_target:
    depends_on:
      - pis_target
  pts_openfda:
    depends_on:
      - pis_openfda
  pts_so:
    depends_on:
      - pis_so

  # ETL STEPS
  etl_expression:
    num_partitions: 4
    depends_on:
      - pts_expression
  etl_go:
    num_partitions: 1
    depends_on:
      - pis_go
  etl_reactome:
    num_partitions: 1
    depends_on:
      - pis_reactome

  etl_otar:
    ppp_only: true
    depends_on:
      - pis_otar
      - pts_disease
  etl_target:
    num_partitions: 10
    depends_on:
      - pts_disease
      - pts_target
      - etl_reactome

  etl_drug:
    num_partitions: 1
    depends_on:
      - pis_drug
      - pts_disease
      - etl_target
  etl_search_facet:
    depends_on:
      - pts_disease
      - etl_go
      - etl_target
  etl_interaction:
    depends_on:
      - pis_interaction
      - etl_target
  etl_mouse_phenotype:
    num_partitions: 1
    depends_on:
      - etl_target
      - pis_mouse_phenotype

  etl_openfda:
    depends_on:
      - pts_openfda
      - etl_drug
  etl_literature:
    num_partitions: 1000
    depends_on:
      - pis_literature
      - etl_drug
  etl_pharmacogenomics:
    num_partitions: 1
    depends_on:
      - pis_pharmacogenomics
      - etl_drug
  etl_target_engine:
    depends_on:
      - pis_target_engine
      - etl_drug

  etl_evidence:
    num_partitions: 100
    depends_on:
      - pis_evidence
      - etl_literature
      - gentropy_l2g_evidence
    depends_on_ppp:
      - pis_evidence_ppp

  etl_association:
    depends_on:
      - etl_evidence
  etl_association_otf:
    depends_on:
      - etl_evidence
  etl_known_drug:
    num_partitions: 2
    depends_on:
      - etl_evidence

  etl_search:
    depends_on:
      - etl_association
      - gentropy_variant
  etl_search_ebi:
    depends_on:
      - etl_association

  # GENTROPY STEPS
  gentropy_biosample:
    depends_on:
      - pis_biosample

  gentropy_study:
    depends_on:
      - pts_target
      - pts_disease
      - etl_target
      - gentropy_biosample

  gentropy_credible_set:
    depends_on:
      - gentropy_study

  gentropy_colocalisation_coloc:
    depends_on:
      - gentropy_credible_set
  gentropy_colocalisation_ecaviar:
    depends_on:
      - gentropy_credible_set
  gentropy_variant_partition:
    depends_on:
      - pis_evidence
      - pis_pharmacogenomics
      - gentropy_credible_set

  gentropy_variant_annotation:
    depends_on:
      - gentropy_variant_partition

  gentropy_variant:
    depends_on:
      - gentropy_variant_annotation

  gentropy_l2g_feature_matrix:
    depends_on:
      - gentropy_colocalisation_coloc
      - gentropy_colocalisation_ecaviar
      - gentropy_variant

  gentropy_l2g_training:
    depends_on:
      - pis_l2g
      - etl_interaction
      - gentropy_credible_set
      - gentropy_variant
      - gentropy_l2g_feature_matrix

  gentropy_l2g_prediction:
    depends_on:
      - gentropy_l2g_feature_matrix
      - gentropy_l2g_training

  gentropy_l2g_evidence:
    depends_on:
      - gentropy_l2g_prediction
