---
release_name: '26.03-test'

# If `is_dev` is true:
#   * the bucket used for the run will be `open-targets-pipeline-runs`
#   * the prefix inside the bucket will be `run_name`
#         which defaults to a timestamp if not provided.
is_dev: true
run_name: 'ds/26.03-test5'

# Whether this will be a partner preview platform release (PPP)
is_ppp: false

# Versions for software and data
pis_version: '26.03.0-dev.7'
pts_version: '26.03.0-dev.43'
etl_version: '26.03.0-dev5'
gentropy_version: '3.2.0-rc.4'
vep_version: 'release_115.2'
chembl_version: '36'
efo_version: '3.87.0'
ensembl_version: '115'
gencode_version: '49'
depmap_version: '2025Q2'
hpo_version: '2026-02-16'
mondo_version: '2026-02-03'
ot_curation: '26.03.0'
probes_drugs_version: '02_2025'
gnomad_version: '4.1'

# Dependency graph
# ----------------
# The following section defines the dependencies between the different steps in
# the pipeline.
#
# IMPORTANT: any dependency change has to be reflected here _manually_.
#
# IMPORTANT: only direct dependencies are defined. Take care when removing one,
#      and always double check if instead of just deleting, you have to change
#      it for another step that is further upstream.
#
# Note: steps that can run in parallel are separated in blocks by a blank line,
#      which means each block depends on the previous block.
#
# It could be possible to generate this automatically from the file input for
# each step, but given the current fast pace of changes throughout the whole
# pipeline, it is not worth the effort to implement this until things have
# stabilised.
#
steps:
  # PIS STEPS
  pis_encode:
  pis_clinical_report:
  pis_biosample:
  pis_disease:
  pis_drug:
  pis_impc:
  pis_ontoma:
  pis_evidence_expression_atlas:
  pis_evidence_cancer_biomarkers:
  pis_evidence_clingen:
  pis_evidence_cosmic:
  pis_evidence_project_score:
  pis_evidence_crispr_screens:
  pis_evidence_eva:
  pis_evidence_gene_burden:
  pis_evidence_gene2phenotype:
  pis_evidence_panel_app:
  pis_evidence_orphanet:
  pis_evidence_reactome:
  pis_evidence_uniprot_literature:
  pis_evidence_uniprot_variants:
  pis_evidence_intogen:
  pis_evidence_ppp:
    ppp_only: true
  pis_expression:
  pis_go:
  pis_interaction:
  pis_enhancer_to_gene:
  pis_l2g:
  pis_literature:
  pis_openfda:
  pis_otar:
    ppp_only: true
  pis_pharmacogenetics:
  pis_reactome:
  pis_so:
  pis_target:
  pis_target_prioritisation:
  # PTS STEPS
  pts_go:
    depends_on:
      - pis_go
  pts_disease:
    depends_on:
      - pis_disease
  pts_ontoma:
    depends_on:
      - pis_ontoma
      - pts_disease
  pts_expression:
    depends_on:
      - pis_expression
  pts_mouse_phenotype:
    depends_on:
      - etl_target
  pts_chemical_probes:
    depends_on:
      - pis_target
      - pts_chembl_molecule
  pts_coding_variant:
    depends_on:
      - gentropy_variant
      - pts_association
      - pts_pharmacogenetics
  pts_openfda:
    depends_on:
      - pis_openfda
  pts_so:
    depends_on:
      - pis_so
  pts_target:
    depends_on:
      - pis_target
  pts_target_safety:
    depends_on:
      - pts_pharmacogenetics
  pts_target_gene_essentiality:
    depends_on:
      - pis_target
  pts_pharmacogenetics:
    depends_on:
      - pis_pharmacogenetics
      - pts_ontoma
      - pts_chembl_molecule
      - pts_drug_mechanism_of_action
  # Evidence not processed by PTS
  pts_evidence_postprocess_europepmc:
    depends_on:
      - etl_literature
      - pis_literature
      - etl_target
      - pts_disease
  pts_evidence_postprocess_gwas_credible_sets:
    depends_on:
      - gentropy_l2g_evidence
      - pis_literature
      - pts_disease
      - etl_target
      - pis_literature
  pts_evidence_postprocess_expression_atlas:
    depends_on:
      - pis_evidence_expression_atlas
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_cosmic:
    depends_on:
      - pis_evidence_cosmic
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_clinvar:
    depends_on:
      - pis_evidence_eva
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_clinvar_somatic:
    depends_on:
      - pis_evidence_eva
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_reactome:
    depends_on:
      - pis_evidence_reactome
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_uniprot_literature:
    depends_on:
      - pis_evidence_uniprot_literature
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_uniprot_variants:
    depends_on:
      - pis_evidence_uniprot_variants
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_encore:
    ppp_only: true
    depends_on:
      - pis_evidence_ppp # TODO: split
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_postprocess_validation_lab:
    ppp_only: true
    depends_on:
      - pis_evidence_ppp # TODO: split
      - etl_target
      - pts_disease
  # Evidence processed by PTS
  pts_evidence_project_score:
    depends_on:
      - pis_evidence_project_score
      - pts_ontoma
  pts_evidence_postprocess_project_score:
    depends_on:
      - pts_evidence_project_score
      - etl_target
      - pts_disease
  pts_evidence_gene_burden:
    depends_on:
      - pis_evidence_gene_burden
      - pts_ontoma
  pts_evidence_postprocess_gene_burden:
    depends_on:
      - pts_evidence_gene_burden
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_clinical_precedence:
    depends_on:
      - pts_clinical_report
      - pts_drug_mechanism_of_action
  pts_evidence_postprocess_clinical_precedence:
    depends_on:
      - pts_evidence_clinical_precedence
  pts_evidence_cancer_biomarkers:
    depends_on:
      - pis_evidence_cancer_biomarkers
      - pts_drug_molecule
  pts_evidence_postprocess_cancer_biomarkers:
    depends_on:
      - pts_evidence_cancer_biomarkers
      - pts_disease
      - pis_literature
      - etl_target
  pts_evidence_orphanet:
    depends_on:
      - pis_evidence_orphanet
      - pts_ontoma
  pts_evidence_postprocess_orphanet:
    depends_on:
      - pts_evidence_orphanet
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_clingen:
    depends_on:
      - pis_evidence_clingen
      - pts_ontoma
  pts_evidence_postprocess_clingen:
    depends_on:
      - pts_evidence_clingen
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_impc:
    depends_on:
      - pis_impc
      - pts_ontoma
  pts_evidence_postprocess_impc:
    num_partitions: 100
    depends_on:
      - pts_evidence_impc
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_panel_app:
    depends_on:
      - pis_evidence_panel_app
      - pts_ontoma
  pts_evidence_postprocess_panel_app:
    depends_on:
      - pts_evidence_panel_app
      - etl_target
      - pis_literature
      - pts_disease
  pts_evidence_crispr_screens:
    depends_on:
      - pis_evidence_crispr_screens
  pts_evidence_postprocess_crispr_screens:
    depends_on:
      - pts_evidence_crispr_screens
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_gene2phenotype:
    depends_on:
      - pis_evidence_gene2phenotype
      - pts_ontoma
  pts_evidence_postprocess_gene2phenotype:
    depends_on:
      - pts_evidence_gene2phenotype
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_intogen:
    depends_on:
      - pis_evidence_intogen
  pts_evidence_postprocess_intogen:
    depends_on:
      - pts_evidence_intogen
      - etl_target
      - pts_disease
      - pis_literature
  pts_evidence_ot_crispr:
    ppp_only: true
    depends_on:
      - pis_evidence_ppp
  pts_evidence_postprocess_ot_crispr:
    ppp_only: true
    depends_on:
      - pts_evidence_ot_crispr
      - etl_target
      - pts_disease
      - pis_literature

  # clinical mining updates:
  pts_drug_warning:
    depends_on:
      - pis_drug
  pts_chembl_molecule:
    depends_on:
      - pis_drug
  pts_drug_mechanism_of_action:
    depends_on:
      - pis_drug
      - pts_target
  pts_drug_molecule:
    depends_on:
      - pts_chemical_probes
      - pts_drug_mechanism_of_action
      - pts_clinical_report
  pts_clinical_report:
    depends_on:
      - pis_clinical_report
      - pts_chembl_molecule
      - pts_disease
      - pts_drug_warning
  pts_clinical_indication:
    depends_on:
      - pts_clinical_report
  pts_clinical_target:
    depends_on:
      - pts_clinical_report
      - pts_drug_mechanism_of_action
  pts_target_prioritisation:
    depends_on:
      - pts_drug_molecule
      - pts_drug_mechanism_of_action
      - pis_target_prioritisation
  pts_association:
    ppp_only: false
    depends_on:
      - pts_evidence_postprocess_impc
      - pts_evidence_postprocess_europepmc
      - pts_evidence_postprocess_gwas_credible_sets
      - pts_evidence_postprocess_expression_atlas
      - pts_evidence_postprocess_cancer_biomarkers
      - pts_evidence_postprocess_clinical_precedence
      - pts_evidence_postprocess_clingen
      - pts_evidence_postprocess_cosmic
      - pts_evidence_postprocess_project_score
      - pts_evidence_postprocess_crispr_screens
      - pts_evidence_postprocess_clinvar
      - pts_evidence_postprocess_clinvar_somatic
      - pts_evidence_postprocess_gene_burden
      - pts_evidence_postprocess_gene2phenotype
      - pts_evidence_postprocess_panel_app
      - pts_evidence_postprocess_orphanet
      - pts_evidence_postprocess_intogen
      - pts_evidence_postprocess_reactome
      - pts_evidence_postprocess_uniprot_literature
      - pts_evidence_postprocess_uniprot_variants
    depends_on_ppp:
      - pts_evidence_postprocess_ot_crispr
      - pts_evidence_postprocess_encore
      - pts_evidence_postprocess_validation_lab
  pts_association_timeseries_view:
    ppp_only: true
    depends_on:
      - pts_association
  pts_association_otf:
    ppp_only: false
    depends_on:
      - pts_association
  # pts_release_metrics:
  #   depends_on:
  #     - pts_association
  # ETL STEPS
  etl_expression:
    num_partitions: 4
    depends_on:
      - pts_expression
  etl_reactome:
    num_partitions: 1
    depends_on:
      - pis_reactome
  etl_otar:
    ppp_only: true
    depends_on:
      - pis_otar
      - pts_disease
  etl_target:
    num_partitions: 10
    depends_on:
      - pts_disease
      - pts_target
      - etl_reactome
      - pts_target_safety
      - pts_target_gene_essentiality
  etl_search_facet:
    depends_on:
      - pts_disease
      - pts_go
      - etl_target
  etl_interaction:
    depends_on:
      - pis_interaction
      - etl_target
  etl_openfda:
    depends_on:
      - pts_openfda
      - pts_drug_molecule
  etl_literature:
    num_partitions: 1000
    depends_on:
      - pis_literature
      - pts_drug_molecule

  etl_search:
    depends_on:
      - pts_association
      - gentropy_variant
  etl_search_ebi:
    depends_on:
      - pts_association

  # GENTROPY STEPS
  gentropy_biosample:
    depends_on:
      - pis_biosample
  gentropy_enhancer_to_gene:
    depends_on:
      - pis_encode
      - etl_target
      - gentropy_biosample
  gentropy_study:
    depends_on:
      - pts_target
      - pts_disease
      - etl_target
      - gentropy_biosample
  gentropy_credible_set:
    depends_on:
      - gentropy_study
  gentropy_colocalisation:
    num_partitions: 200
    depends_on:
      - gentropy_credible_set
  gentropy_variant_partition:
    depends_on:
      - pts_pharmacogenetics
      - gentropy_credible_set
      - pis_evidence_uniprot_variants
      - pis_evidence_eva
  gentropy_variant_annotation:
    depends_on:
      - gentropy_variant_partition
  gentropy_variant:
    depends_on:
      - gentropy_variant_annotation
  gentropy_l2g_feature_matrix:
    depends_on:
      - gentropy_colocalisation
      - gentropy_variant
      - gentropy_enhancer_to_gene
  gentropy_l2g_training:
    depends_on:
      - pis_l2g
      - etl_interaction
      - gentropy_l2g_feature_matrix
  gentropy_l2g_prediction:
    depends_on:
      - gentropy_l2g_training
  gentropy_l2g_evidence:
    depends_on:
      - gentropy_l2g_prediction
