---
# PPP overrides

# This file overrides the unified pipeline configuration for the gentropy.yaml step configuration for
# the PPP run
steps:
  study:
    params:
      step.study_index_path:
        - '{{release_uri}}/input/study/GCCA'
        - '{{release_uri}}/input/study/GCSS-pics'
        - '{{release_uri}}/input/study/GCSS-susie'
        - '{{release_uri}}/input/study/eQTL-Catalogue'
        - '{{release_uri}}/input/study/UKB-PPP'
        - '{{release_uri}}/input/study/FinnGen'
        - '{{release_uri}}/input/study/FinnGen-UKB-MVP'
        # PPP
        - '{{release_uri}}/input/study/microglia'
        - '{{release_uri}}/input/study/MAGE_OTAR'
        - '{{release_uri}}/input/study/IBDverse'

  credible_set:
    params:
      step.study_locus_path:
        - '{{release_uri}}/input/credible_set/GCCA'
        - '{{release_uri}}/input/credible_set/GCSS-pics'
        - '{{release_uri}}/input/credible_set/GCSS-susie'
        - '{{release_uri}}/input/credible_set/eQTL-Catalogue'
        - '{{release_uri}}/input/credible_set/UKB-PPP'
        - '{{release_uri}}/input/credible_set/FinnGen'
        - '{{release_uri}}/input/credible_set/FinnGen-UKB-MVP'
        # PPP
        - '{{release_uri}}/input/credible_set/microglia'
        - '{{release_uri}}/input/credible_set/MAGE_OTAR'
        - '{{release_uri}}/input/credible_set/IBDverse'

  variant:
    params:
      step.variant_annotations_path:
        - gs://gnomad_data_2/v4.1/variant_index
        # PPP
        - gs://otar013-ppp/OTAR2075_lof_curation/lof_curation_variant_annotations
