---
# PPP overrides

# This file overrides the unified pipeline configuration for the gentropy.yaml step configuration for
# the PPP run
steps:
  study:
    params:
      step.study_index_path:
        - gs://gwas_catalog_top_hits/study_index
        - gs://gwas_catalog_sumstats_susie/study_index
        - gs://gwas_catalog_sumstats_pics/study_index
        - gs://eqtl_catalogue_data/study_index
        - gs://ukb_ppp_eur_data/study_index
        - gs://finngen_data/r12/study_index
        # PPP
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/microglia/gentropy/study_index/*
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/MAGE_OTAR/gentropy/study_index/*
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/IBDverse/gentropy/study_index/*
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/GTEx_v10_majiq/gentropy/output/study_index/*
        - gs://finngen_ukb_mvp_meta_data/study_index/
      step.invalid_qc_reasons:
        - UNRESOLVED_TARGET
        - UNRESOLVED_DISEASE
        - UNKNOWN_STUDY_TYPE
        - DUPLICATED_STUDY
        - UNKNOWN_BIOSAMPLE
        - FAILED_MEAN_BETA_CHECK
        - FAILED_PZ_CHECK
        - FAILED_GC_LAMBDA_CHECK
        - NO_OT_CURATION
        - CASE_CASE_STUDY_DESIGN
        # PPP
        - DEPRECATED_PROJECT
      step.deprecated_project_ids:
        - GTEx # GTEx v8 studies from eqtl Catalogue are swapped with newly ingested GTEX-v10
  credible_set:
    params:
      step.study_locus_path:
        - gs://gwas_catalog_top_hits/credible_sets/
        - gs://gwas_catalog_sumstats_pics/credible_sets/
        - gs://gwas_catalog_sumstats_susie/credible_set_clean/20260130/
        - gs://eqtl_catalogue_data/credible_set_datasets/eqtl_catalogue_susie_patched_v2/
        - gs://ukb_ppp_eur_data/credible_set_clean/20250129/
        - gs://finngen_data/r12/credible_set_datasets/susie/
        # PPP
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/microglia/gentropy/study_locus/*
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/MAGE_OTAR/gentropy/study_locus/*
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/IBDverse/gentropy/study_locus/*
        - gs://eqtl_catalogue_processed_otar_internal_data/otar2077/GTEx_v10_majiq/gentropy/output/study_locus/*
        - gs://finngen_ukb_mvp_meta_data/credible_sets/

  variant:
    params:
      step.variant_annotations_path:
        - gs://gnomad_data_2/v4.1/variant_index
        # PPP
        - gs://otar013-ppp/OTAR2075_lof_curation/lof_curation_variant_annotations
