cluster_name: otg-finngen-ukb-meta
steps:
  - id: finngen_ukb_meta_ingestion
    params:
      raw_study_index_path_from_tsv: gs://gentropy-tmp/batch/output/finngen_ukb_meta/study_index.tsv
      raw_summary_stats_path: gs://gentropy-tmp/batch/output/finngen_ukb_meta/summary_stats.parquet
      variant_annotation_path: gs://genetics_etl_python_playground/output/python_etl/parquet/XX.XX/variant_annotation
      tmp_variant_annotation_path: gs://gentropy-tmp/variant_annotation
      study_index_output_path: gs://finngen_ukb_meta_data/study_index
      summary_stats_output_path: gs://finngen_ukb_meta_data/summary_stats
