- id: "ot_gene_index"
- id: "ot_variant_index"
- id: "ot_variant_to_gene"
  prerequisites:
    - "ot_variant_index"
    - "ot_gene_index"
- id: "ot_colocalisation_ecaviar"
- id: "ot_colocalisation_coloc"
- id: "ot_locus_to_gene_train"
  prerequisites:
    - "ot_variant_index"
    - "ot_variant_to_gene"
    - "ot_colocalisation_ecaviar"
    - "ot_colocalisation_coloc"
- id: "ot_locus_to_gene_predict"
  prerequisites:
    - "ot_locus_to_gene_train"
    - "ot_variant_index"
    - "ot_variant_to_gene"
    - "ot_colocalisation_ecaviar"
    - "ot_colocalisation_coloc"
