---

environment_specs:
  - name: Staging
    vars:
      gentropy_ref: 2.2.0-rc.2
      release_dir: gs://ot_orchestration/releases/25.02_freeze1
      input_dir: gs://open-targets-pre-data-releases/24.12-uo_test-3/input
      # NOTE: Patched target index is required, as existing target index does not contain all columns requested by the original gene index - see https://github.com/opentargets/gentropy/pull/946
      target_index: gs://ot-team/vivien/gentropy_patched_datasets/target_index_with_tss_column
      output_path: gs://open-targets-pre-data-releases/24.12-uo_test-3/output

      # data buckets
      gc_susie: gs://gwas_catalog_sumstats_susie
      gc_pics: gs://gwas_catalog_sumstats_pics
      top_hits: gs://gwas_catalog_top_hits
      eqtl: gs://eqtl_catalogue_data
      ukb: gs://ukb_ppp_eur_data
      finngen: gs://finngen_data/r12
      gnomad: gs://gnomad_data_2
env: Staging

l2g_gold_standard_path: gs://genetics_etl_python_playground/input/l2g/gold_standard/curation.json
dataproc:
  cluster_metadata:
    GENTROPY_REF: 'v{gentropy_ref}'
  cluster_name: otg-etl
  autoscaling_policy: otg-efm
  worker_machine_type: n1-highmem-32
  num_workers: 20
  allow_efm: true

nodes:
  - id: biosample_index
    kind: Task
    prerequisites: []
    params:
      step: biosample_index
      step.cell_ontology_input_path: '{input_dir}/biosamples/cl.json'
      step.uberon_input_path: '{input_dir}/biosamples/uberon.json'
      step.efo_input_path: '{input_dir}/biosamples/efo.json'
      step.biosample_index_path: '{release_dir}/biosample_index'
      step.session.write_mode: overwrite
  - id: study_validation
    kind: Task
    prerequisites:
      - biosample_index
    params:
      step: study_validation
      step.study_index_path:
        - '{top_hits}/study_index'
        - '{gc_susie}/study_index'
        - '{gc_pics}/study_index'
        - '{eqtl}/study_index'
        - '{ukb}/study_index'
        - '{finngen}/study_index'
      step.target_index_path: '{target_index}'
      step.disease_index_path: '{output_path}/etl/parquet/diseases'
      step.valid_study_index_path: '{release_dir}/study_index'
      step.invalid_study_index_path: '{release_dir}/invalid_study_index'
      step.biosample_index_path: '{release_dir}/biosample_index'
      step.invalid_qc_reasons:
        - UNRESOLVED_TARGET
        - UNRESOLVED_DISEASE
        - UNKNOWN_STUDY_TYPE
        - DUPLICATED_STUDY
        - UNKNOWN_BIOSAMPLE
        - FAILED_MEAN_BETA_CHECK
        - FAILED_PZ_CHECK
        - FAILED_GC_LAMBDA_CHECK
        - NO_OT_CURATION

  - id: credible_set_validation
    kind: Task
    prerequisites:
      - study_validation
    params:
      step: credible_set_validation
      step.study_index_path: '{release_dir}/study_index'
      step.study_locus_path:
        - '{top_hits}/credible_sets/'
        - '{gc_pics}/credible_sets/'
        - '{gc_susie}/credible_set_clean/20250204/'
        - '{eqtl}/credible_set_datasets/eqtl_catalogue_susie_patched_v2/'
        - '{ukb}/credible_set_clean/20250129/'
        - '{finngen}/credible_set_datasets/susie/'
      step.valid_study_locus_path: '{release_dir}/credible_set'
      step.invalid_study_locus_path: '{release_dir}/invalid_credible_set'
      step.target_index_path: '{target_index}'
      step.trans_qtl_threshold: 5_000_000
      step.invalid_qc_reasons:
        - DUPLICATED_STUDYLOCUS_ID
        - AMBIGUOUS_STUDY
        - MISSING_STUDY
        - NO_GENOMIC_LOCATION_FLAG
        - COMPOSITE_FLAG
        - INCONSISTENCY_FLAG
        - SUBSIGNIFICANT_FLAG
        - LD_CLUMPED
        - IN_MHC
        - REDUNDANT_PICS_TOP_HIT
        - EXPLAINED_BY_SUSIE
        - WINDOW_CLUMPED
        - NON_MAPPED_VARIANT_FLAG
        - INVALID_VARIANT_IDENTIFIER
        - INVALID_CHROMOSOME
        - TOP_HIT_AND_SUMMARY_STATS
      step.session.write_mode: overwrite

  - id: convert_variants_to_vcf
    kind: Task
    prerequisites:
      - credible_set_validation
    params:
      step: variant_to_vcf
      step.source_paths:
        - '{input_dir}/evidence-files/uniprot.json.gz'
        - '{input_dir}/evidence-files/eva.json.gz'
        - '{input_dir}/pharmacogenomics-inputs/pharmacogenomics.json.gz'
        - '{release_dir}/credible_set'
      step.source_formats:
        - json
        - json
        - json
        - parquet
      step.output_path: '{release_dir}/variants/partitioned_variants'
      step.partition_size: 2_000 # approximate num of variants per partition!

  - id: variant_annotation
    kind: Task
    prerequisites:
      - convert_variants_to_vcf
    google_batch:
      entrypoint: /bin/sh
      image: 'europe-west1-docker.pkg.dev/open-targets-genetics-dev/gentropy-app/custom_ensembl_vep:{GENTROPY_REF}'
      resource_specs:
        cpu_milli: 2000
        memory_mib: 2000
        boot_disk_mib: 10000
      task_specs:
        max_retry_count: 1
        max_run_duration: '2h'
      policy_specs:
        machine_type: n1-standard-4
    params:
      vep_cache_path: gs://genetics_etl_python_playground/vep/cache
      vcf_input_path: '{release_dir}/variants/partitioned_variants'
      vep_output_path: '{release_dir}/variants/annotated_variants'

  - id: variant_index
    prerequisites:
      - variant_annotation
    params:
      step: variant_index
      step.vep_output_json_path: '{release_dir}/variants/annotated_variants'
      step.gnomad_variant_annotations_path: '{gnomad}/v4.1/variant_index'
      step.variant_index_path: '{release_dir}/variant_index'
      step.amino_acid_change_annotations: []

  - id: colocalisation_coloc
    prerequisites:
      - variant_index
    params:
      step: colocalisation
      step.credible_set_path: '{release_dir}/credible_set'
      step.coloc_path: '{release_dir}/colocalisation/'
      step.colocalisation_method: Coloc
      +step.colocalisation_method_params: '{priorc1: 1e-4, priorc2: 1e-4, priorc12: 1e-5}'
      +step.session.extended_spark_conf: "{spark.executor.memory: '25g',spark.executor.memoryOverhead: '1g', spark.executor.cores: '4'}"
      step.session.write_mode: overwrite

  - id: colocalisation_ecaviar
    prerequisites:
      - variant_index
      - colocalisation_coloc
    params:
      step: colocalisation
      step.credible_set_path: '{release_dir}/credible_set'
      step.coloc_path: '{release_dir}/colocalisation'
      step.colocalisation_method: ECaviar
      +step.session.extended_spark_conf: "{spark.executor.memory: '25g', spark.executor.memoryOverhead: '1g', spark.executor.cores: '4'}"
      step.session.write_mode: overwrite

  - id: l2g_feature_matrix
    prerequisites:
      - colocalisation_coloc
      - colocalisation_ecaviar
      - variant_index
    params:
      step: locus_to_gene_feature_matrix
      step.credible_set_path: '{release_dir}/credible_set'
      step.variant_index_path: '{release_dir}/variant_index'
      step.colocalisation_path: '{release_dir}/colocalisation'
      step.study_index_path: '{release_dir}/study_index'
      step.target_index_path: '{target_index}'
      step.feature_matrix_path: '{release_dir}/locus_to_gene_feature_matrix'
      +step.session.extended_spark_conf: "{spark.sql.autoBroadcastJoinThreshold:'-1'}"
      step.session.write_mode: overwrite

  - id: l2g_train
    prerequisites:
      - l2g_feature_matrix
    params:
      step: locus_to_gene
      step.run_mode: train
      step.wandb_run_name: 24.11_freeze10
      step.hf_hub_repo_id: opentargets/locus_to_gene
      step.hf_model_commit_message: 'chore: update model based on 24.11_freeze10 run'
      step.model_path: '{release_dir}/locus_to_gene_model/classifier.skops'
      step.credible_set_path: '{release_dir}/credible_set'
      step.variant_index_path: '{release_dir}/variant_index'
      step.feature_matrix_path: '{release_dir}/locus_to_gene_feature_matrix'
      step.gold_standard_curation_path: gs://genetics_etl_python_playground/input/l2g/gold_standard/curation.json
      step.gene_interactions_path: gs://genetics_etl_python_playground/static_assets/interaction # OTP 23.12 data
      step.hyperparameters.n_estimators: 100
      step.hyperparameters.max_depth: 5
      step.hyperparameters.loss: log_loss
      +step.session.extended_spark_conf: "{spark.kryoserializer.buffer.max:500m, spark.sql.autoBroadcastJoinThreshold:'-1'}"

  - id: l2g_predict
    prerequisites:
      - l2g_train
    params:
      step: locus_to_gene
      step.run_mode: predict
      step.predictions_path: '{release_dir}/locus_to_gene_predictions'
      step.feature_matrix_path: '{release_dir}/locus_to_gene_feature_matrix'
      step.credible_set_path: '{release_dir}/credible_set'
      step.download_from_hub: false
      step.l2g_threshold: 0.05
      step.model_path: gs://ot_orchestration/benchmarks/l2g/fm0/v5.1_best_cv/locus_to_gene_model/classifier.skops
      step.hf_hub_repo_id: opentargets/locus_to_gene
      step.session.write_mode: overwrite

  - id: l2g_evidence
    prerequisites:
      - l2g_predict
    params:
      step: locus_to_gene_evidence
      step.evidence_output_path: '{release_dir}/locus_to_gene_evidence'
      step.locus_to_gene_predictions_path: '{release_dir}/locus_to_gene_predictions'
      step.credible_set_path: '{release_dir}/credible_sets/'
      step.study_index_path: '{release_dir}/study_index'
      step.locus_to_gene_threshold: 0.05
      step.session.write_mode: overwrite

  - id: l2g_associations
    params:
      step: locus_to_gene_associations
      step.evidence_input_path: '{release_dir}/locus_to_gene_evidence'
      step.disease_index_path: '{output_path}/etl/parquet/diseases'
      step.direct_associations_output_path: '{release_dir}/locus_to_gene_associations/direct_associations'
      step.indirect_associations_output_path: '{release_dir}/locus_to_gene_associations/indirect_associations'
      step.session.spark_uri: yarn
      step.session.write_mode: overwrite

    prerequisites:
      - l2g_evidence
