---
dataproc:
  python_main_module: gs://genetics_etl_python_playground/initialisation/cli.py
  cluster_metadata:
    GENTROPY_REF: v2.0.2-rc.3
  cluster_init_script: gs://genetics_etl_python_playground/initialisation/install_dependencies_on_cluster.sh
  cluster_name: gnomad-preprocess
  autoscaling_policy: otg-etl
  allow_efm: false
  num_workers: 2

nodes:
  - id: ld_index
    kind: Task
    prerequisites: []
    params:
      step.ld_index_out: gs://genetics_etl_python_playground/static_assets/ld_index
      # The version will of the gnomad will be inferred from ld_matrix_template and appended to the ld_index_out.
      step.use_version_from_input: false
  - id: gnomad_variants
    kind: Task
    prerequisites: [ld_index]
    params:
      step: gnomad_variants
      step.variant_annotation_path: gs://gnomad_data_2/v4.1/variant_index
      step.use_version_from_input: false
