dataproc:
  cluster_name: otg-gwascatalog-sumstats-pics
  autoscaling_policy: otg-preprocess-gwascatalog
  python_main_module: gs://genetics_etl_python_playground/initialisation/gentropy/dev/cli.py
  cluster_metadata:
    PACKAGE: gs://genetics_etl_python_playground/initialisation/gentropy/dev/gentropy-0.0.0-py3-none-any.whl
  cluster_init_script: gs://genetics_etl_python_playground/initialisation/gentropy/dev/install_dependencies_on_cluster.sh
  num_workers: 5

nodes:
  - id: summary_statistics_processing
    kind: TaskGroup
    prerequisites: []
    nodes:
      - id: gwas_catalog_study_index
        kind: Task
        prerequisites: []
        params:
          step: gwas_catalog_study_index
          step.catalog_study_files:
            - gs://gwas_catalog_inputs/gwas_catalog_download_studies.tsv
          step.catalog_ancestry_files:
            - gs://gwas_catalog_inputs/gwas_catalog_download_ancestries.tsv
          step.study_index_path: gs://gwas_catalog_sumstats_pics/study_index
          step.session.write_mode: overwrite
          step.session.spark_uri: yarn
      - id: window_based_clumping
        kind: Task
        prerequisites: []
        params:
          step: window_based_clumping
          step.summary_statistics_input_path: gs://gwas_catalog_inputs/harmonised_summary_statistics
          step.study_locus_output_path: gs://gwas_catalog_sumstats_pics/study_locus_window_based_clumped
          step.session.write_mode: overwrite
          step.session.spark_uri: yarn
      - id: ld_based_clumping
        kind: Task
        prerequisites:
          - window_based_clumping
        params:
          step: ld_based_clumping
          step.ld_index_path: gs://genetics_etl_python_playground/static_assets/ld_index
          step.study_locus_input_path: gs://gwas_catalog_sumstats_pics/study_locus_window_based_clumped
          step.clumped_study_locus_output_path: gs://gwas_catalog_sumstats_pics/study_locus_ld_clumped
          step.study_index_path: gs://gwas_catalog_sumstats_pics/study_index
          step.session.write_mode: overwrite
          step.session.spark_uri: yarn
      - id: pics
        kind: Task
        prerequisites:
          - ld_based_clumping
        params:
          step: pics
          step.study_locus_ld_annotated_in: gs://gwas_catalog_sumstats_pics/study_locus_ld_clumped
          step.picsed_study_locus_out: gs://gwas_catalog_sumstats_pics/credible_sets
          step.session.write_mode: overwrite
          step.session.spark_uri: yarn
