steps:
  disease:
    input: input/ontology-inputs/ontology-efo.json
    output: output/etl/diseases.parquet

  # input/expression-inputs/normal_tissue.tsv.gz, expression-inputs/tissue-translation-map.json
  expression: # TODO multifile
    input: input/expression-inputs
    output: output/etl/expression

  # these must process the all the homologues
  homologue: # TODO multifile
    input: input/target-inputs/homologue
    output: output/etl/homologue

  # these must process the 1500 openfda event files
  openfda:
    input: input/fda-inputs
    output: output/etl/fda

  so:
    input: input/so-inputs/so.json
    output: output/etl/so.parquet

  # there are 4 ontoform transformers that go here
  target: # TODO multifile
    input: input/target-inputs
    output: output/etl/target
