nodes:
  - id: generate_manifests
    kind: Task
    prerequisites: []
    params:
      collected_loci_path: gs://ot_orchestration/ukb_ppp_eur_data/study_locus_datasets/locus_breaker_clumping
      manifest_prefix: gs://ot_orchestration/ukb_ppp_eur_data/finemapping_manifests
      output_path: gs://ot_orchestration/ukb_ppp_eur_data/credible_set_datasets/ukb_ppp_eur_susie
      max_records_per_chunk: 100_000

  - id: finemapping_batch_job
    kind: Task
    prerequisites:
    - generate_manifests
    params:
      study_index_path: gs://ukb_ppp_eur_data/study_index
    google_batch:
      entrypoint: /bin/sh
      image: europe-west1-docker.pkg.dev/open-targets-genetics-dev/gentropy-app/gentropy:dev
      resource_specs:
        cpu_milli: 4000
        memory_mib: 25000
        boot_disk_mib: 600000
      task_specs:
        max_retry_count: 5
        max_run_duration: "7200s"
      policy_specs:
        machine_type: n1-highmem-4
