# The bucket where the pipeline will work in
gcs_url: gs://open-targets-pre-data-releases/24.06dev-test-ontoform

# Versions of the pipeline components
pis_version: 24.6.0
ontoform_version: 24.0.0-alpha.2
etl_version: 24.1.0
gentropy_commit: 93de448

# Versions of the data sources
chembl_version: '34'
efo_version: v3.70.0
ensembl_version: '112'

# Whether this is a PPP run of the pipeline
is_ppp: false

# Dependency graph
# ----------------
# The following section defines the dependencies between the different steps in
# the pipeline. PIS steps are not here, as they have no dependencies.
#
# IMPORTANT: any dependency change has to be reflected here _manually_.
#
# Note: steps that can run in parallel are separated in blocks by a blank line
#      which effectively means blocks depend on the previous block.
#
# IMPORTANT NOTE: only direct dependencies are defined. Take care when removing
#      one, and always double check if instead of just deleting, you have to
#      change it for another step that is further upstream.
#
# It could be possible to generate this automatically from the file input for
# each step, but given the current fast pace of changes throughout the whole
# pipeline, it is not worth the effort to implement this until things have
# stabilised.
#
steps:
  # ONTOFORM STEPS
  ontoform_disease:
    depends_on:
      - pis_disease
  ontoform_expression:
    depends_on:
      - pis_expression
  ontoform_homologue:
    depends_on:
      - pis_homologue
  ontoform_openfda:
    depends_on:
      - pis_openfda
  ontoform_so:
    depends_on:
      - pis_so
  ontoform_target:
    depends_on:
      - pis_target

  # ETL STEPS
  etl_go:
    depends_on:
      - pis_go
  etl_disease:
    depends_on:
      - ontoform_disease
  etl_expression:
    depends_on:
      - ontoform_expression
  etl_reactome:
    depends_on:
      - pis_reactome

  etl_otar:
    depends_on:
      - etl_disease
    depends_on_ppp: # this extra dependency is added in ppp runs
      - pis_otar
  etl_target:
    depends_on:
      - ontoform_homologue
      - ontoform_target
      - etl_reactome

  etl_drug:
    depends_on:
      - pis_drug
      - etl_target
      - etl_disease
  etl_facetsearch:
    depends_on:
      - etl_target
      - etl_disease
      - etl_go
  etl_interactions:
    depends_on:
      - pis_interactions
      - etl_target
  etl_targetValidation:
    depends_on:
      - pis_mouse_phenotypes
      - etl_target

  etl_fda:
    depends_on:
      - ontoform_openfda
      - etl_drug
  etl_literature:
    depends_on:
      - pis_literature
      - etl_drug
  etl_pharmacogenomics:
    depends_on:
      - pis_pharmacogenomics
      - etl_drug
  etl_targetengine:
    depends_on:
      - pis_target_engine
      - etl_drug

  etl_evidence:
    depends_on:
      - pis_evidence
      - etl_literature
    depends_on_ppp:
      - pis_ppp_evidence
      - genetics_l2g_evidence

  etl_association:
    depends_on:
      - etl_evidence
  etl_associationOTF:
    depends_on:
      - etl_evidence

  etl_knownDrug:
    depends_on:
      - etl_evidence

  etl_ebisearch:
    depends_on:
      - etl_association
  etl_search:
    depends_on:
      - etl_association
    depends_on_ppp:
      - genetics_variant_index

  # GENETIC STEPS
  genetics_biosample_index:
    depends_on:
      - pis_biosample
  genetics_gene_index:
    depends_on:
      - etl_target

  genetics_study_validation:
    depends_on:
      - pis_target
      - etl_diseases
      - genetics_biosample_index
      - genetics_gene_index

  genetics_credible_set_validation:
    depends_on:
      - genetics_study_validation

  genetics_variant_conversion:
    depends_on:
      - pis_evidence
      - pis_pharmacogenomics
      - genetics_credible_set_validation
  genetics_colocalisation_coloc:
    depends_on:
      - genetics_credible_set_validation
  genetics_colocalisation_ecaviar:
    depends_on:
      - genetics_credible_set_validation

  genetics_variant_annotation:
    depends_on:
      - genetics_variant_conversion

  genetics_variant_index:
    depends_on:
      - genetics_variant_annotation

  genetics_l2g_feature_matrix:
    depends_on:
      - genetics_colocalisation_coloc
      - genetics_colocalisation_ecaviar
      - genetics_variant_index

  genetics_l2g_train:
    depends_on:
      - etl_interactions
      - genetics_l2g_feature_matrix

  genetics_l2g_predict:
    depends_on:
      - genetics_l2g_train

  genetics_l2g_evidence:
    depends_on:
      - genetics_l2g_predict
