---
# The bucket where the pipeline will work in
gcs_url: gs://open-targets-pre-data-releases/24.12-uo_test-3

# Versions of the pipeline components
pis_version: 24.6.4
ontoform_version: 24.1.0-alpha.7
etl_version: 24.2.0-alpha.4
gentropy_version: v2.0.0rc3
vep_version: v2.0.0rc3

# Versions of the data sources
chembl_version: '34'
efo_version: v3.70.0
ensembl_version: '113'

# Whether this is a PPP run of the pipeline
is_ppp: true

# Dependency graph
# ----------------
# The following section defines the dependencies between the different steps in
# the pipeline.
#
# IMPORTANT: any dependency change has to be reflected here _manually_.
#
# IMPORTANT: only direct dependencies are defined. Take care when removing one,
#      and always double check if instead of just deleting, you have to change
#      it for another step that is further upstream.
#
# Note: steps that can run in parallel are separated in blocks by a blank line,
#      which means each block depends on the previous block.
#
# It could be possible to generate this automatically from the file input for
# each step, but given the current fast pace of changes throughout the whole
# pipeline, it is not worth the effort to implement this until things have
# stabilised.
#
steps:
  # PIS STEPS
  pis_baseline_expression:
  pis_biosample:
  pis_disease:
  pis_drug:
  pis_evidence:
  pis_expression:
  pis_go:
  pis_homologue:
  pis_interaction:
  pis_literature:
  pis_mouse_phenotypes:
  pis_openfda:
  pis_otar:
    ppp_only: true
  pis_pharmacogenomics:
  pis_ppp_evidence:
    ppp_only: true
  pis_reactome:
  pis_so:
  pis_target:
  pis_target_engine:

  # ONTOFORM STEPS
  ontoform_disease:
    depends_on:
      - pis_disease
  ontoform_expression:
    depends_on:
      - pis_expression
  ontoform_homologue:
    depends_on:
      - pis_homologue
  ontoform_openfda:
    depends_on:
      - pis_openfda
  ontoform_so:
    depends_on:
      - pis_so
  ontoform_target:
    depends_on:
      - pis_target

  # ETL STEPS
  etl_go:
    depends_on:
      - pis_go
  etl_expression:
    depends_on:
      - ontoform_expression
  etl_reactome:
    depends_on:
      - pis_reactome

  etl_otar:
    ppp_only: true
    depends_on:
      - ontoform_disease
      - pis_otar
  etl_target:
    depends_on:
      - ontoform_homologue
      - ontoform_target
      - etl_reactome

  etl_drug:
    depends_on:
      - pis_drug
      - etl_target
      - ontoform_disease
  etl_facetsearch:
    depends_on:
      - etl_target
      - ontoform_disease
      - etl_go
  etl_interaction:
    depends_on:
      - pis_interaction
      - etl_target
  etl_targetValidation:
    depends_on:
      - pis_mouse_phenotypes
      - etl_target

  etl_fda:
    depends_on:
      - ontoform_openfda
      - etl_drug
  etl_literature:
    depends_on:
      - pis_literature
      - etl_drug
  etl_pharmacogenomics:
    depends_on:
      - pis_pharmacogenomics
      - etl_drug
  etl_targetengine:
    depends_on:
      - pis_target_engine
      - etl_drug

  etl_evidence:
    depends_on:
      - pis_evidence
      - etl_literature
      - gentropy_l2g_evidence
    depends_on_ppp:
      - pis_ppp_evidence

  etl_association:
    depends_on:
      - etl_evidence
  etl_associationOTF:
    depends_on:
      - etl_evidence

  etl_knownDrug:
    depends_on:
      - etl_evidence

  etl_ebisearch:
    depends_on:
      - etl_association
  etl_search:
    depends_on:
      - etl_association
      - gentropy_variant_index

  # GENTROPY STEPS
  gentropy_biosample_index:
    depends_on:
      - pis_biosample

  gentropy_study_validation:
    depends_on:
      - ontoform_target
      - ontoform_disease
      - gentropy_biosample_index
      - etl_target

  gentropy_credible_set_validation:
    depends_on:
      - gentropy_study_validation

  gentropy_variant_conversion:
    depends_on:
      - pis_evidence
      - pis_pharmacogenomics
      - gentropy_credible_set_validation

  gentropy_variant_annotation:
    depends_on:
      - gentropy_variant_conversion

  gentropy_variant_index:
    depends_on:
      - gentropy_variant_annotation

  gentropy_colocalisation_coloc:
    depends_on:
      - gentropy_variant_index
  gentropy_colocalisation_ecaviar:
    depends_on:
      - gentropy_variant_index

  gentropy_l2g_feature_matrix:
    depends_on:
      - gentropy_colocalisation_coloc
      - gentropy_colocalisation_ecaviar
      - gentropy_variant_index

  gentropy_l2g_predict:
    depends_on:
      - etl_interaction
      - gentropy_l2g_feature_matrix

  gentropy_l2g_evidence:
    depends_on:
      - gentropy_l2g_predict
